#!/usr/bin/env python3
"""Generate a byte-exact MASM skeleton .asm for a MicroProse driver overlay
(*GRAPHIC.EXE / *SOUND.EXE) from its binary + mzmap routine map.

The drivers have no call-reachable exports (entries come from the OvlHeader
jump table), so the skeleton is intentionally simple:

- seg000 (data): OvlHeader emitted as asm (`dw seg seg001`, `dw offset
  <handler>`) so LINK reproduces the original stored values AND relocation
  entries; remaining bytes emitted verbatim.
- seg001 (code): each map routine becomes `name proc far` + `db` bytes with
  the ndisasm decoding as a comment, `endp` -- byte-exact by construction.
  Bytes not claimed by any routine are emitted as data.

Usage: drv2asm.py DRIVER.EXE map/x.map out.asm
"""
import re
import struct
import subprocess
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
from compare_exe import load_image


def parse_map(path):
    segs, routines = {}, []
    for line in open(path):
        m = re.match(r'^(\w+) (CODE|DATA|STACK) ([0-9a-f]+)', line)
        if m:
            segs[m.group(1)] = int(m.group(3), 16)
            continue
        m = re.match(r'^([\w.]+): (\w+) (NEAR|FAR) ([0-9a-f]+)-([0-9a-f]+)', line)
        if m:
            routines.append(dict(name=m.group(1), seg=m.group(2), type=m.group(3),
                                 lo=int(m.group(4), 16), hi=int(m.group(5), 16)))
    return segs, routines


def disasm_span(data, org):
    """ndisasm a span -> [(bytes, text)] roughly aligned per instruction."""
    p = subprocess.run(['ndisasm', '-b16', '-o', hex(org), '/dev/stdin'],
                       input=data, capture_output=True)
    out = []
    for line in p.stdout.decode().splitlines():
        m = re.match(r'([0-9A-F]+)\s+([0-9A-F]+)\s+(.*)', line)
        if m:
            out.append((bytes.fromhex(m.group(2)), m.group(3)))
    return out


def emit_db(f, data, comment=''):
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        f.write('        db ' + ','.join(f'0{b:02X}h' if b > 9 else str(b)
                                         for b in chunk))
        f.write('\n')


def emit_code(f, data, org):
    """emit instructions: bytes as db + disasm text as comments"""
    pos = 0
    for insn, text in disasm_span(data, org):
        # keep comment short
        f.write(f'        db ' + ','.join(f'0{b:02X}h' for b in insn)
                + f'        ; {text}\n')
        pos += len(insn)
    if pos < len(data):  # tail bytes ndisasm couldn't decode
        emit_db(f, data[pos:])


def main():
    exe, mapfile, outasm = sys.argv[1], sys.argv[2], sys.argv[3]
    img = load_image(exe)
    segs, routines = parse_map(mapfile)

    # seg order by paragraph; seg000 = para 0 (header/data), seg001 = code
    seg_names = {name: f'seg{i:03d}' for i, (name, para) in
                 enumerate(sorted(segs.items(), key=lambda kv: kv[1]))}
    seg_para = {name: para for name, para in segs.items()}
    code_seg_name = max(seg_para, key=seg_para.get)  # last seg = code (seg001)
    data_seg_name = min(seg_para, key=seg_para.get)

    # header fields
    code_para, base_para, first, size1, size2, count = struct.unpack_from('<6H', img, 0x18)
    slots = struct.unpack_from(f'<{count}H', img, 0x24)
    slot_off = {w: i + first for i, w in enumerate(slots)}
    entry_by_off = {r['lo']: r['name'] for r in routines if r['seg'] == code_seg_name}

    code_lin0 = seg_para[code_seg_name] * 16
    data_end = code_lin0

    with open(outasm, 'w') as f:
        f.write('; auto-generated driver skeleton: ' + os.path.basename(exe) + '\n')
        f.write('; generated by tools/drv2asm.py from ' + mapfile + '\n\n')

        # ---- data segment (seg000): header + tables, verbatim ----
        f.write(f'{seg_names[data_seg_name]} segment byte public \'CODE\'\n')
        f.write('        assume cs:nothing, ds:nothing, es:nothing, ss:nothing\n')
        f.write('start   label byte\n')
        sig = img[:0x18]
        sigstr = ''.join(chr(b) for b in sig.split(b'\0')[0])
        f.write(f"        db '{sigstr}'\n")
        pad = img[len(sigstr):0x18]
        if pad:
            emit_db(f, pad)
        f.write(f'        dw seg {seg_names[code_seg_name]}        ; code_segment\n')
        f.write(f'        dw seg {seg_names[data_seg_name]}        ; base_segment\n')
        f.write(f'        dw {first}, 0{size1:X}h, 0{size2:X}h, {count} '
                '; first_slot, size1, size2, jump_count\n')
        # slot array -> offsets of named handlers
        i = 0x24
        for w in slots:
            tgt = entry_by_off.get(w)
            if tgt:
                f.write(f'        dw offset {tgt} '
                        f'; slot {i // 2 - 0x12:#04x}\n')
            else:
                f.write(f'        dw 0{w:X}h                ; slot {i // 2 - 0x12:#04x} (mid-proc)\n')
            i += 2
        # remaining data bytes verbatim
        emit_db(f, img[i:data_end])
        f.write(f'{seg_names[data_seg_name]} ends\n\n')

        # ---- code segment (seg001) ----
        f.write(f'{seg_names[code_seg_name]} segment byte public \'CODE\'\n')
        f.write(f'        assume cs:{seg_names[code_seg_name]}, ds:{seg_names[data_seg_name]}, es:nothing, ss:nothing\n')
        pos = 0
        for r in sorted(routines, key=lambda r: r['lo']):
            if r['seg'] != code_seg_name:
                continue
            if r['lo'] > pos:  # unclaimed gap
                emit_db(f, img[code_lin0 + pos: code_lin0 + r['lo']])
            if r['lo'] < pos:
                continue  # routine overlaps an earlier extent; skip dup bytes
            body = img[code_lin0 + r['lo']: code_lin0 + r['hi'] + 1]
            f.write(f"{r['name']} proc {r['type'].lower()}\n")
            emit_code(f, body, r['lo'])
            f.write(f"{r['name']} endp\n")
            pos = r['hi'] + 1
        if pos < len(img) - code_lin0:
            emit_db(f, img[code_lin0 + pos:])
        f.write(f'{seg_names[code_seg_name]} ends\n')
        f.write('        end\n')
    print(f'wrote {outasm}')


if __name__ == '__main__':
    main()
