#!/usr/bin/env python3
"""Generate an IDAPython rename script from mzretools map files that were
annotated by mzdup + apply_dup_names.py.

Emits a python script that renames IDA functions by linear address.
Usage: map2ida.py file.map [file2.map ...] > rename_ida.py

Each map routine line: `name: Seg NEAR|FAR start-end ...`
Segment line:          `Seg CODE|DATA|STACK addr` (addr = segment paragraphs)
Linear address = seg_addr * 16 + offset, minus the map's relocation base.
The map is written relocated to load segment 0x1000 (mzmap reverses it on
save), so linear addresses here equal file offsets in the load module,
which equal the IDA image offsets (image base 0x1000:0000).
"""
import re
import sys

SEG_RE = re.compile(r"^([$_a-zA-Z0-9]+) (CODE|DATA|STACK) ([0-9a-fA-F]{1,4})")
RT_RE = re.compile(r"^([$_a-zA-Z0-9]+): ([$_a-zA-Z0-9]+) (NEAR|FAR) ([0-9a-fA-F]{1,4})-")
COMMENT_RE = re.compile(r"potential duplicate of routine (\S+) .*differs by (\d+)")

HEADER = '''# Auto-generated by map2ida.py - run inside IDA (File -> Script file)
import idaapi, ida_name, ida_segment

def lin2ea(lin):
    """load-module linear address -> IDA effective address"""
    s = ida_segment.get_first_seg()
    while s:
        base = ida_segment.get_segm_start(s)
        end = ida_segment.get_segm_end(s)
        # IDA image base 0x1000:0000 -> linear 0x10000
        if base - 0x10000 <= lin < end - 0x10000:
            return base + (lin - (base - 0x10000))
        s = ida_segment.get_next_seg(s.start_ea)
    return idaapi.BADADDR

RENAMES = [
'''

FOOTER = ''']
for lin, name, dist in RENAMES:
    ea = lin2ea(lin)
    if ea == idaapi.BADADDR:
        print("no segment for %x (%s)" % (lin, name))
        continue
    old = ida_name.get_name(ea)
    if ida_name.set_name(ea, name, ida_name.SN_CHECK):
        print("%05x: %s -> %s (dist %s)" % (lin, old, name, dist))
    else:
        print("%05x: FAILED rename %s -> %s" % (lin, old, name))
'''


def emit(path):
    segs = {}
    pending_name = None
    pending_dist = None
    out = []
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.rstrip("\n")
            m = SEG_RE.match(line)
            if m:
                segs[m.group(1)] = int(m.group(3), 16)
                continue
            m = COMMENT_RE.search(line)
            if m:
                pending_name = m.group(1)
                pending_dist = m.group(2)
                continue
            m = RT_RE.match(line)
            if m:
                name, seg, kind, off = m.group(1), m.group(2), m.group(3), int(m.group(4), 16)
                if seg not in segs:
                    continue
                lin = segs[seg] * 16 + off
                if pending_name:
                    # use matched f15 name as comment source; routine already renamed
                    out.append((lin, name, pending_dist, pending_name))
                    pending_name = None
    return out


print(HEADER)
for p in sys.argv[1:]:
    print("    # --- %s" % p)
    for lin, name, dist, src in emit(p):
        print('    (0x%x, "%s", %s),  # src: %s' % (lin, name, dist, src))
print(FOOTER)
