# Auto-generated by map2ida.py - run inside IDA (File -> Script file)
import idaapi, ida_name, ida_segment

def lin2ea(lin):
    """load-module linear address -> IDA effective address"""
    s = ida_segment.get_first_seg()
    while s:
        base = ida_segment.get_segm_start(s)
        end = ida_segment.get_segm_end(s)
        # IDA image base 0x1000:0000 -> linear 0x10000
        if base - 0x10000 <= lin < end - 0x10000:
            return base + (lin - (base - 0x10000))
        s = ida_segment.get_next_seg(s.start_ea)
    return idaapi.BADADDR

RENAMES = [

    # --- map/start.map
    (0x87d, "cleanup", 0),  # src: cleanup
    (0x4569, "mystrcat", 0),  # src: mystrcat
    (0x4643, "intDispatch", 0),  # src: intDispatch
    (0x4909, "clearRect", 1),  # src: clearRect
    (0x49c3, "clearDirtyRects", 0),  # src: clearDirtyRects
    (0x4d8c, "installCBreakHandler", 0),  # src: installCBreakHandler
    (0x4f7a, "openFile", 0),  # src: openFile
    (0x5028, "closeFile", 0),  # src: fileClose
    (0x5075, "readFile2", 1),  # src: readFile2
    (0x5172, "openBlitClosePic", 0),  # src: openBlitClosePic
    (0x5260, "picBlit", 0),  # src: showPicFile
    (0x53ae, "decodePic", 0),  # src: decodePic
    (0x5418, "decodePicRow", 0),  # src: decodePicRow
    (0x5442, "picReadDataAndMakeDict", 0),  # src: picReadDataAndMakeDict
    (0x5489, "picMakeDict", 0),  # src: picMakeDict
    (0x54bf, "doPicDecode", 0),  # src: doPicDecode
    (0x5538, "dictionaryLookup", 0),  # src: dictionaryLookup
    (0x6a1e, "allocBuffer", 0),  # src: allocBuffer
    (0x6a52, "freeBuffer", 0),  # src: freeBuffer
    (0x6a7a, "dos_alloc", 0),  # src: dos_alloc
    (0x6aa0, "dos_free", 0),  # src: dos_free
    (0x893c, "itemDistance", 2),  # src: itemDistance
    (0x896a, "positionUnit", 4),  # src: positionUnit
    (0x8a36, "rangeApprox", 0),  # src: rangeApprox
    (0x8a98, "parseWorld", 8),  # src: parseWorld
    (0x8c04, "exportWorldToComm", 1),  # src: exportWorldToComm
    (0x8d76, "computeBearing", 0),  # src: computeBearing
    (0x8f32, "memAppend", 0),  # src: memAppend
]
for lin, name, dist in RENAMES:
    ea = lin2ea(lin)
    if ea == idaapi.BADADDR:
        print("no segment for %x (%s)" % (lin, name))
        continue
    old = ida_name.get_name(ea)
    if ida_name.set_name(ea, name, ida_name.SN_CHECK):
        print("%05x: %s -> %s (dist %s)" % (lin, old, name, dist))
    else:
        print("%05x: FAILED rename %s -> %s" % (lin, old, name))

