# Auto-generated by map2ida.py - run inside IDA (File -> Script file)
import idaapi, ida_name, ida_segment

def lin2ea(lin):
    """load-module linear address -> IDA effective address"""
    s = ida_segment.get_first_seg()
    while s:
        base = ida_segment.get_segm_start(s)
        end = ida_segment.get_segm_end(s)
        # IDA image base 0x1000:0000 -> linear 0x10000
        if base - 0x10000 <= lin < end - 0x10000:
            return base + (lin - (base - 0x10000))
        s = ida_segment.get_next_seg(s.start_ea)
    return idaapi.BADADDR

RENAMES = [

    # --- map/su.map
    (0x12ff, "mystrcat", 0),  # src: mystrcat
    (0x13d9, "intDispatch", 0),  # src: intDispatch
    (0x1704, "installCBreakHandler", 0),  # src: installCBreakHandler
]
for lin, name, dist in RENAMES:
    ea = lin2ea(lin)
    if ea == idaapi.BADADDR:
        print("no segment for %x (%s)" % (lin, name))
        continue
    old = ida_name.get_name(ea)
    if ida_name.set_name(ea, name, ida_name.SN_CHECK):
        print("%05x: %s -> %s (dist %s)" % (lin, old, name, dist))
    else:
        print("%05x: FAILED rename %s -> %s" % (lin, old, name))

