# Auto-generated by map2ida.py - run inside IDA (File -> Script file)
import idaapi, ida_name, ida_segment

def lin2ea(lin):
    """load-module linear address -> IDA effective address"""
    s = ida_segment.get_first_seg()
    while s:
        base = ida_segment.get_segm_start(s)
        end = ida_segment.get_segm_end(s)
        # IDA image base 0x1000:0000 -> linear 0x10000
        if base - 0x10000 <= lin < end - 0x10000:
            return base + (lin - (base - 0x10000))
        s = ida_segment.get_next_seg(s.start_ea)
    return idaapi.BADADDR

RENAMES = [

    # --- map/end.map
    (0x27f, "initGraphics", 3),  # src: initGraphics
    (0x2e5, "cleanup", 0),  # src: cleanup
    (0x31a, "loadWorldStrings", 0),  # src: loadWorldStrings
    (0x36c, "readWorldData", 0),  # src: readWorldData
    (0x455, "loadWorldData", 0),  # src: loadWorldData
    (0x4d3, "memAppend", 0),  # src: memAppend
    (0x51b, "waitForKeyOrJoy", 2),  # src: waitForKeyOrJoy
    (0x60a, "drawStringAt", 1),  # src: drawStringAt
    (0x910, "my_ltoa", 2),  # src: my_ltoa
    (0xa47, "my_itoa", 2),  # src: my_itoa
    (0xc23, "mystrcat", 0),  # src: mystrcat
    (0xcfd, "intDispatch", 0),  # src: intDispatch
    (0xf25, "clearRect", 1),  # src: clearRect
    (0x107d, "clearDirtyRects", 0),  # src: clearDirtyRects
    (0x11fe, "clipAndDrawLine", 0),  # src: clipAndDrawLine
    (0x1372, "computeLineOutcode", 0),  # src: computeOutcode
    (0x13b4, "installCBreakHandler", 0),  # src: installCBreakHandler
    (0x15a2, "openFile", 0),  # src: openFile
    (0x1650, "closeFile", 0),  # src: fileClose
    (0x169d, "readFile2", 1),  # src: readFile2
    (0x179a, "openBlitClosePic", 0),  # src: openBlitClosePic
    (0x1888, "picBlit", 0),  # src: showPicFile
    (0x18fa, "decodePic", 0),  # src: decodePic
    (0x1a40, "decodePicRow", 0),  # src: decodePicRow
    (0x1a6a, "picReadDataAndMakeDict", 0),  # src: picReadDataAndMakeDict
    (0x1ab1, "picMakeDict", 0),  # src: picMakeDict
    (0x1ae7, "doPicDecode", 0),  # src: doPicDecode
    (0x1b60, "dictionaryLookup", 0),  # src: dictionaryLookup
    (0x3046, "allocBuffer", 0),  # src: allocBuffer
    (0x307a, "freeBuffer", 0),  # src: freeBuffer
    (0x30a2, "dos_alloc", 0),  # src: dos_alloc
    (0x30c8, "dos_free", 0),  # src: dos_free
    (0x3fa2, "blinkWidget", 0),  # src: blinkWidget
    (0x5417, "formatFlightTime", 1),  # src: formatFlightTime
    (0x5526, "plotMapPoint", 0),  # src: plotMapPoint
    (0x557d, "drawMapLine", 1),  # src: drawFlightLine
    (0x55c4, "drawClippedLine", 1),  # src: drawClippedLine
    (0x55ef, "drawClippedLineEx", 1),  # src: drawClippedLineEx
    (0x728a, "computeMissionResult", 0),  # src: computeMissionResult
]
for lin, name, dist in RENAMES:
    ea = lin2ea(lin)
    if ea == idaapi.BADADDR:
        print("no segment for %x (%s)" % (lin, name))
        continue
    old = ida_name.get_name(ea)
    if ida_name.set_name(ea, name, ida_name.SN_CHECK):
        print("%05x: %s -> %s (dist %s)" % (lin, old, name, dist))
    else:
        print("%05x: FAILED rename %s -> %s" % (lin, old, name))

