# Auto-generated by map2ida.py - run inside IDA (File -> Script file)
import idaapi, ida_name, ida_segment

def lin2ea(lin):
    """load-module linear address -> IDA effective address"""
    s = ida_segment.get_first_seg()
    while s:
        base = ida_segment.get_segm_start(s)
        end = ida_segment.get_segm_end(s)
        # IDA image base 0x1000:0000 -> linear 0x10000
        if base - 0x10000 <= lin < end - 0x10000:
            return base + (lin - (base - 0x10000))
        s = ida_segment.get_next_seg(s.start_ea)
    return idaapi.BADADDR

RENAMES = [

    # --- map/egame.map
    (0x504, "loadColorPalette", 0),  # src: loadColorPalette
    (0x1068, "replaceExtension", 0),  # src: replaceExtension
    (0x1092, "findNearestTileObject", 7),  # src: findNearestTileObject
    (0x12dc, "addTileEntry", 1),  # src: addTileEntry
    (0x131e, "lookupTileEntry", 1),  # src: lookupTileEntry
    (0x1372, "drawNearestTileObject", 0),  # src: drawNearestTileObject
    (0x1516, "renderMapTerrain", 0),  # src: renderMapTerrain
    (0x1564, "drawMapTiles", 0),  # src: drawMapTiles
    (0x16f0, "computeTileBounds", 1),  # src: computeTileBounds
    (0x174c, "worldToTileIndex", 1),  # src: worldToTileIndex
    (0x1802, "drawModelPoint", 0),  # src: drawModelPoint
    (0x1846, "buildVertexSignMask", 0),  # src: buildVertexSignMask
    (0x18ce, "projectModelVertices", 1),  # src: projectModelVertices
    (0x19ea, "setup3DTransform", 2),  # src: setup3DTransform
    (0x1a7a, "setupViewport", 5),  # src: setupViewport
    (0x1b32, "setViewRotation", 1),  # src: setViewRotation
    (0x1c83, "installCBreakHandler", 0),  # src: installCBreakHandler
    (0x304a, "applyRotationDelta", 1),  # src: applyRotationDelta
    (0x3085, "computeAttitudeAngles", 4),  # src: computeAttitudeAngles
    (0x3277, "signedRatio16", 1),  # src: signedRatio16
    (0x32f1, "valueToAngle", 3),  # src: valueToAngle
    (0x3387, "isqrt", 1),  # src: isqrt
    (0x3d8f, "waitForKeyPress", 2),  # src: waitForKeyPress
    (0x4ef7, "moveDataFar", 1),  # src: moveDataFar
    (0x4f18, "moveStuff", 4),  # src: moveStuff
    (0x57db, "updateThreatAlert", 3),  # src: updateThreatAlert
    (0x7aaf, "markTargetReached", 5),  # src: markTargetReached
    (0x7b46, "bombTarget", 2),  # src: bombTarget
    (0x8bea, "readMapPixelColor", 1),  # src: readMapPixelColor
    (0x8d2a, "drawMapLine", 1),  # src: drawFlightLine
    (0x8d71, "drawFullscreenLine", 1),  # src: drawFullscreenLine
    (0x8d9a, "drawViewportLine", 0),  # src: drawViewportLine
    (0x8f10, "drawScreenLineOnePage", 1),  # src: drawScreenLineOnePage
    (0x8fb2, "fillRectBoth", 1),  # src: fillRectBoth
    (0x91b4, "drawStringBothPages", 1),  # src: drawStringBothPages
    (0x9257, "drawNumber", 1),  # src: drawNumber
    (0x9282, "readScreenPixel", 2),  # src: readScreenPixel
    (0x978c, "drawMapMarkerBox", 0),  # src: drawMapMarkerBox
    (0x9810, "projectMapPoint", 0),  # src: projectMapPoint
    (0x98bc, "blitGaugeSprite", 0),  # src: blitGaugeSprite
    (0xa23f, "cacheScopePanel", 1),  # src: cacheScopePanel
    (0xa26c, "restoreScopePanel", 1),  # src: restoreScopePanel
    (0xa2c5, "captureScopePanel", 1),  # src: captureScopePanel
    (0xc681, "drawTargetLabel", 1),  # src: drawTargetLabel
    (0xc719, "buildRangeString", 1),  # src: buildRangeString
    (0xcab4, "computeTargetBearing", 2),  # src: computeTargetBearing
    (0xcb53, "isTargetOverWater", 1),  # src: isTargetOverWater
    (0xcb8c, "load15Flt3d3", 4),  # src: load15Flt3d3
    (0xcc7e, "drawWorldObject", 11),  # src: drawWorldObject
    (0xcdde, "drawTargetView", 15),  # src: drawTargetView
    (0xd1c8, "shapeDataOffset", 2),  # src: shapeDataOffset
    (0xd23b, "rangeApprox", 0),  # src: rangeApprox
    (0xd484, "readAxisInput", 1),  # src: readAxisInput
    (0xdef2, "makeSound", 1),  # src: makeSound
    (0xdf3c, "recalcTimeScale", 4),  # src: recalcTimeScale
    (0xe212, "openFile", 0),  # src: openFile
    (0xe2c0, "closeFile", 0),  # src: fileClose
    (0xe40a, "openBlitClosePic", 0),  # src: openBlitClosePic
    (0xe4f8, "picBlit", 0),  # src: showPicFile
    (0xe6b0, "decodePicRow", 0),  # src: decodePicRow
    (0xe6da, "picReadDataAndMakeDict", 0),  # src: picReadDataAndMakeDict
    (0xe721, "picMakeDict", 0),  # src: picMakeDict
    (0xe757, "doPicDecode", 0),  # src: doPicDecode
    (0xe7d0, "dictionaryLookup", 0),  # src: dictionaryLookup
    (0xff0a, "projectVertexToScreen", 0),  # src: projectVertexToScreen
    (0xffef, "clipLineSegment", 0),  # src: clipLineSegment
    (0x100d1, "clipLineSubdivP1Outside", 0),  # src: clipLineSubdivP1Outside
    (0x1012f, "writeClippedStart", 0),  # src: writeClippedStart
    (0x10164, "writeClippedEnd", 0),  # src: writeClippedEnd
    (0x1019a, "rejectClippedLine", 0),  # src: rejectClippedLine
    (0x101c6, "clipPointInside", 0),  # src: clipPointInside
    (0x10215, "clipComputeOutcode", 0),  # src: clipComputeOutcode
    (0x1024c, "clampToClipEdge", 0),  # src: clampToClipEdge
    (0x102a0, "clipMidpointSubdivide", 0),  # src: clipMidpointSubdivide
    (0x10316, "clipLineMidpoint", 0),  # src: clipLineMidpoint
    (0x10384, "pointOnClipEdge", 0),  # src: pointOnClipEdge
    (0x103bf, "computeClipOutcode", 0),  # src: computeClipOutcode
    (0x1046e, "decodeRleEdgeRow", 0),  # src: decodeRleEdgeRow
    (0x10510, "renderHorizonSky", 0),  # src: renderHorizonSky
    (0x10716, "projectSceneObject", 0),  # src: projectSceneObject
    (0x1079a, "transformAndCullObject", 0),  # src: transformAndCullObject
    (0x1089b, "skipDisplayListByLod", 0),  # src: skipDisplayListByLod
    (0x10912, "insertSortedObject", 0),  # src: insertSortedObject
    (0x109f2, "renderSortedList", 0),  # src: renderSortedList
    (0x10a79, "processSceneObject", 1),  # src: processSceneObject
    (0x10b47, "rotatePoint3d", 0),  # src: rotatePoint3d
    (0x10c88, "transformModelVertices", 0),  # src: transformModelVertices
    (0x10f84, "transformVertexList", 0),  # src: transformVertexList
    (0x1106c, "projectModelEdges", 0),  # src: projectModelEdges
    (0x11116, "clipEdgeNearPlane", 0),  # src: clipEdgeNearPlane
    (0x111f3, "buildRotationMatrix", 0),  # src: buildRotationMatrix
    (0x1130f, "buildInverseRotationMatrix", 0),  # src: buildInverseRotationMatrix
    (0x11461, "multiplyMatrix3x3", 0),  # src: multiplyMatrix3x3
    (0x115fe, "renderPrimitiveList", 0),  # src: renderPrimitiveList
    (0x11689, "renderPrimitiveCommand", 0),  # src: renderPrimitiveCommand
    (0x117ce, "drawPrimitiveEdges", 0),  # src: drawPrimitiveEdges
    (0x11a58, "fillSpanRect", 0),  # src: fillSpanRect
    (0x11b4a, "clipLineCohenSutherland", 0),  # src: clipLineCohenSutherland
    (0x11cd6, "computeLineOutcode", 0),  # src: computeOutcode
    (0x11d34, "resetScanlineSpansImpl", 0),  # src: resetScanlineSpansImpl
    (0x11d6a, "clampScanlineSpan", 0),  # src: clampScanlineSpan
    (0x11dc8, "rasterizeEdgeSpan", 0),  # src: rasterizeEdgeSpan
    (0x11ebc, "clipAndRasterizeEdgeImpl", 4),  # src: clipAndRasterizeEdgeImpl
    (0x12092, "drawInstrumentGauges", 3),  # src: drawInstrumentGauges
    (0x12d6e, "setInt9Handler", 0),  # src: setInt9Handler
]
for lin, name, dist in RENAMES:
    ea = lin2ea(lin)
    if ea == idaapi.BADADDR:
        print("no segment for %x (%s)" % (lin, name))
        continue
    old = ida_name.get_name(ea)
    if ida_name.set_name(ea, name, ida_name.SN_CHECK):
        print("%05x: %s -> %s (dist %s)" % (lin, old, name, dist))
    else:
        print("%05x: FAILED rename %s -> %s" % (lin, old, name))

